name: "Set Environment Variables"
description: "Set environment variables based on inputs"

inputs:
  environment:
    description: "The environment to set"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set BASE_URL
      shell: bash
      env:
        API_CHALLENGES_LIVE: ${{ github.secrets.API_CHALLENGES_LIVE }}
        API_CHALLENGES_TEST: ${{ github.secrets.API_CHALLENGES_TEST }}
      run: |
        if [ "${{ github.event.inputs.environment }}" == "live" ]; then
          echo "API_BASE_URL=${API_CHALLENGES_LIVE}" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
          echo "API_BASE_URL=${API_CHALLENGES_TEST}" >> $GITHUB_ENV
        else
          echo "Error: Unknown environment '${{ github.eventinputs.environment }}'. Please use 'live' or 'test'." >&2
          exit 1
        fi
