name: "Set Environment Variables"
description: "Set environment variables based on inputs"

inputs:
  environment:
    description: "The environment to set"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set BASE_URL
      shell: bash
      run: |
        if [ "${{inputs.environment}}" == "live" ]; then
          echo "API_BASE_URL=${{vars.API_CHALLENGES_LIVE}}" >> $GITHUB_ENV
        elif [ "${{inputs.environment}}" == "test" ]; then
          echo "API_BASE_URL=${{vars.API_CHALLENGES_TEST}}" >> $GITHUB_ENV
        else
          echo "Error: Unknown environment '${{inputs.environment}}'. Please use 'live' or 'test'." >&2
          exit 1
        fi
